a = input('Digite seu nome completo: ')
nomec = a.strip() #elimina os espaços da esquerda (começo) e da direita (fim)
nometi = nomec.title()
nomema = nomec.upper()
nomemi = nomec.lower()
ql = nomec.split()  #quebra a frase em palavras separadas - ql é uma sequencia de palavras
qpn = len(ql[0])
aux = nomec.replace(' ','')
qnomec = len(aux)
print('Nome completo title: {}'.format(nometi))
print('Nome completo maiúsculo: {}'.format(nomema))
print('Nome completo minúsculo: {}'.format(nomemi))
print('Quantidade de letras do nome completo sem espaços: {}'.format(qnomec))
print('Quantidade de letras do primeiro nome: {}'.format(qpn))
