x = input('Digite algo: ')
print('O que foi digitado é do tipo primitivo: ',type(x))
print('{} é númerico? '.format(x),x.isnumeric())
print('{} é decimal ? '.format(x),x.isdecimal())
print('{} é letra? '.format(x),x.isalpha())
print('{} é alfanumérico? '.format(x),x.isalnum())
print('{} é maiúsculo? '.format(x),x.isupper())
print('{} é minúsculo? '.format(x),x.islower())
print('{} só tem espaços? '.format(x),x.isspace())
print('{} é capitalizada? '.format(x),x.istitle())